POST http://localhost:3001/api/blogs
Content-Type: application/json
Cookie: session= // cookie of the logged in user

{
  "author": "Michael Chan",
  "url": "https://reactpatterns.com/",
  "title":"React patterns",
  "likes": 7
}